### ISSUE TITLE
PCR usages

### ISSUE THREAD

**Issue by kpreiksa** [Aircloak/TrustedGRUB#3]
My corporation uses Trusted Grub for a product we develop. We are trying to figure out the usage of PCRs in our system (which uses several other components besides Trusted Grub). I noticed that you had some documentation as to which PCRs are used by Trusted Grub. However, by looking through the code I was only able to determine that PCRs 8,9,12,13,14 are extended by Trusted Grub. Could you tell me where you found the information about the other PCRs? I am specifically interested in PCRs 4 and 5.

If you did not determine the information I am referring to, could you point me to the source of the documentation?

Thank you!

**Comment by Aviv-z** [comment]
From the Original README of TrustedGRUB-1.1.5:

* PCR 4 contains MBR information and stage1
* PCR 8 contains bootloader information stage2 part1
* PCR 9 contains bootloader information stage2 part2
* PCR 12 contains all commandline arguments from menu.lst and those entered in the shell
* PCR 13 contains all files checked via the checkfile-routine
* PCR 14 contains all files which are actually loaded (e.g., Linux kernel, initrd, modules...)
NOTE: In case you booted via a CD-image, PCR-8 will be empty and PCR-9 will contain
      the whole measurement of the stage2_eltorito-boot-image.

Some other info I have collected:

•PCR 0 to 3 for the BIOS, ROMS...
•PCR 4 contains MBR information and stage1
•PCR 8 contains bootloader information stage2 part1
•PCR 9 contains bootloader information stage2 part2
•PCR 12 contains all commandline arguments from menu.lst and those entered in the shell
•PCR 13 contains all files checked via the checkfile-routine
•PCR 14 contains all files which are actually loaded (e.g., Linux kernel, initrd, modules...)

PCR0 – CRTM, BIOS code, and Host Platform Extensions (Note: CRTM is measured by the processor and initial BIOS code is measured by the ACM – all other measurements made by BIOS or other firmware code – but only after that code had been measured)
PCR1 – Host Platform Configuration
PCR2 – Option ROM Code
PCR3 – Option ROM Configuration and Data
PCR4 – IPL (Initial Program Loader) Code (usually the Master Boot Record – MBR)
PCR5 – IPL Code Configuration and Data (for use by the IPL Code)
PCR6 – State Transition and Wake Events
PCR7 – Host Platform Manufacturer Control

Hope this helps

**Comment by cristianberneanu** [comment]
For a specific machine, you can determine what code and data is measured by looking at the BIOS measurements log:
```
mount -n -t securityfs -o nodev,noexec,nosuid securityfs /sys/kernel/security
cat /sys/kernel/security/tpm0/ascii_bios_measurements
```

If you want the authoritative source for the measurements, read the latest version of the [TCG PC Client Specific Implementation Specification for Conventional BIOS] (http://www.trustedcomputinggroup.org/resources/pc_client_work_group_specific_implementation_specification_for_conventional_bios)

**Comment by kpreiksa** [comment]
Thank you so much. This helped me figure out what is doing some
measurements. We needed to know which pieces of software were touching the
PCRs before our application. This allows us to ensure consistency between
machines. Thank you for the help!

**Comment by kpreiksa** [comment]
I have another question concerning the installation of Stage 2. As I
understand it, Stage 1 is the first 440 bytes of the MBR/first sector of
the hard drive. Where is stage 2 normally installed when not using the
modified script? Why does this change between installations on the same
disk with the same partitioning? The reason I am asking is because we are
using a self-encrypting drive and I also need to understand exactly which
regions on a disk can be encrypted and which need to be unlocked during the
booting process. The partitioning system we use currently allocates only
32K at the beginning of the disk and we notice that when reinstalling
trusted grub, PCRs 4 and 8 do not match. Any help, even documentation links
like the one you provided previously will be appreciated!

**Comment by cristianberneanu** [comment]
Using the original TrustedGRUB method, stage 2 is installed on the root partition and a pointer to it's disk sector location is set inside stage 1, at this location:  https://github.com/cristianberneanu/TrustedGRUB/blob/master/stage1/stage1.S#L101
That is one of the reasons that measurements are not deterministic using the original method.

To get consistent measurements, use the method I described in the README after leaving 1MB unused, at the start of the disk, when partitioning the disk. Also, make sure to set the partition id to 0.
